### ISSUE TITLE
Editing Mii Friendship Level Corrupts Save

### ISSUE THREAD

**Issue by ccc814p** [Brionjv/Tomodachi-Life-Save-Editor#83]
Hello there!
I recently discovered this program.
This program works mostly perfectly fine for everything except for changing the relationship level between two Miis.
I tried editing Mario and Peach to have higher friendship level because Mario thought Peach was interested in him.
Upon doing this, the save corrupted. There are no duplicate lovers/spouses/best friends.
I've read all the other issues and this seems to be an issue with the program itself.
However, I apologize if I am wrong.
Thank you!

**Comment by Brionjv** [comment]
You can try to restore an old save file, edit your Mii, save and close save editor. Edit one Mii by one Mii

**Comment by LoganTheHammer** [comment]
> You can try to restore an old save file, edit your Mii, save and close save editor. Edit one Mii by one Mii

Is the edit mii one by one a guaranteed fix for right now? Does it always work?

**Comment by Elhixsagh** [comment]
I'm having this same issue. I went in to change relationships for my Mii's, and the game corrupted. There also isn't option to make relationship "child" only "parent," so when I make one the parent, they both say parent. Not sure if it even shows any different in game though since it corrupts. 
Also it shows the Mii you are editing also as a Mii relationship option.

**Comment by Brionjv** [comment]
To set "child", Mii must be a kid. To set "parent" Mii must be an adult. Save is corrupted bacause there are probably duplicate parent (more than 2)
